name: animated_book_widget
description: An immersive book-like widget with captivating animations
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter  

dev_dependencies:
  dart_code_metrics: ^5.7.6
  very_good_analysis: ^5.1.0

screenshots:
  - description: Animated Book Widget
    path: screenshots/animated_book_widget.gif
  - description: Animated Book Widget
    path: screenshots/animated_book_widget.png 
  - description: Animated Book Widget
    path: screenshots/animated_book_widget1.gif
  - description: Animated Book Widget
    path: screenshots/animated_book_widget1.png  

flutter:  