name: animated_book_list
description: A Dart Package for comunity the-d-velopers
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter  

dev_dependencies:
  very_good_analysis: ^5.1.0
